version: "3"
services:
  prometheus:
    user: 0:0
    image: prom/prometheus:v2.30.0
    container_name: prometheus
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus/
    # command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    ports:
      - 9100:9100
  grafana:
    user: 0:0
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana
      - ./etc/grafana/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
